{"uuid": "bebb5c14-73bc-4374-b20a-f2951111ebd3", "children": ["b3dd4c18-fd6d-41bc-9acc-b8d0b28c82d7", "e4b38ef1-2728-4020-a68c-a25a41333d29", "66628903-4a90-42ae-a9a2-769105eb03b2", "fd390eda-76f4-408e-81cf-3ce713cb24fa"], "befores": [{"name": "remote_driver", "status": "passed", "start": 1657515842684, "stop": 1657515859316}], "afters": [{"name": "remote_driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Unable to route (DELETE) /session/e5902a8d1c915c951c73023513bec668\n\n", "trace": "  File \"d:\\工具\\python\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\工具\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\selenium_compass\\cases\\test_case_pytest.py\", line 45, in remote_driver\n    driver.quit()\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 955, in quit\n    self.execute(Command.QUIT)\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1657516805406, "stop": 1657516805416}], "start": 1657515842684, "stop": 1657516805416}